{% set name = "param" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: param-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/p/param/param-{{ version }}.tar.gz
  sha256: ba1f7cec6455ea8ad96f641f4082759bf1057dcbe629aa79d956b25973252422

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - param
    - numbergen

about:
  home: https://param.holoviz.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Param: Make your Python code clearer and more reliable by declaring Parameters'
  description: |
    Param is a library providing Parameters: Python attributes
    extended to have features such as type and range checking,
    dynamically generated values, documentation strings, default
    values, etc., each of which is inherited from parent classes
    if not specified in a subclass.
  doc_url: https://param.holoviz.org/
  dev_url: https://github.com/holoviz/param

extra:
  recipe-maintainers:
    - basnijholt
    - jlstevens
    - philippjfr
    - maximlt
