{% set name = "param" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  fn: param-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/param/param-{{ version }}.tar.gz
  sha256: 35d0281c8e3beb6dd469f46ff0b917752a54bed94d1b0c567346c76d0ff59c4a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=2.7

test:
  imports:
    - param
    - numbergen

about:
  home: http://ioam.github.io/param/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Param: Make your Python code clearer and more reliable by declaring Parameters'
  description: |
    Param is a library providing Parameters: Python attributes
    extended to have features such as type and range checking,
    dynamically generated values, documentation strings, default
    values, etc., each of which is inherited from parent classes
    if not specified in a subclass.
  doc_url: https://param.pyviz.org/
  dev_url: https://github.com/ioam/param

extra:
  recipe-maintainers:
    - basnijholt
    - jlstevens
    - philippjfr
